name: CI

on:
  push:
    branches:
      - main  
jobs:
  bulid-and-push-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and Push dev
        uses: docker/build-push-action@v5
        with:
          context: /containers/dev-app
          file: ./Dockerfile
          push: true
          tags: omerteomim/dev-app:latest
      
      - name: Build and Push staging
        uses: docker/build-push-action@v5
        with:
          context: /containers/staging-app
          file: ./Dockerfile
          push: true
          tags: omerteomim/staging-app:latest
      
      - name: Build and Push prod
        uses: docker/build-push-action@v5 
        with:
          context: /containers/prod-app
          file: ./Dockerfile
          push: true
          tags: omerteomim/prod-app:latest